# general settings
name: ESPCN_Vimeo_BDx4
model_type: VideoBaseModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Vimeo
    type: VimeoDataset
    gt_dir: ./dataset/vimeo/vimeo_septuplet/sequences
    lq_dir: ./dataset/vimeo/vimeo_septuplet/BDx4
    meta_info_file: ./dataset/vimeo/vimeo_septuplet/sep_trainlist.txt

    num_frame: 3
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true
    flip_sequence: true

    # data loader
    num_worker_per_gpu: 1
    batch_size_per_gpu: 4
    # dataset_enlarge_ratio: 200
    # prefetch_mode: ~

  val:
    name: Vid4
    type: VideoTestDataset
    gt_dir: ./dataset/Vid4/GT
    lq_dir: ./dataset/Vid4/BDx4

    num_frame: 3  # not needed

# network structures
network:
  type: ESPCN
  num_in_ch: 3
  num_out_ch: 3
  num_ch: 64
  upscale: 4

# path
path:
  pretrain_network: ~
  strict_load: true
  resume_state: ~
  train_state: ./experiments/train/ESPCN
  log: ./experiments/log/ESPCN
  tb_logger: ./experiments/tb_logger/ESPCN

# training settings
train:
  ema_decay: 0.999
  optim:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true