# general settings
name: EDVR_REDSx4
model_type: EDVRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: REDSDataset
    gt_dir: ./datasets/REDS/train_sharp
    lq_dir: ./datasets/REDS/train_sharp_bicubic/X4
    flow_dir: ~
    meta_info_file: ./data/meta_info/meta_info_REDS_train.txt
    # val_partition: Vimeo  # set to 'official' when use the official validation partition

    num_frame: 5
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 1
    batch_size_per_gpu: 4
    # dataset_enlarge_ratio: 200
    # prefetch_mode: ~

  val:
    name: REDS4
    type: VideoTestDataset
    gt_dir: ./datasets/REDS4/GT
    lq_dir: ./datasets/REDS4/sharp_bicubic
    meta_info_file: ./data/meta_info/meta_info_REDS4_test_GT.txt
    # change to 'meta_info_REDSofficial4_test_GT' when use the official validation partition

    # cache_data: false
    num_frame: 5
    padding: reflection_circle

# network structures
network:
  type: EDVR
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 128
  num_frame: 5
  deformable_groups: 8
  num_extract_block: 5
  num_reconstruct_block: 40
  center_frame_idx: ~
  hr_in: false
  with_predeblur: false
  with_tsa: false

# path
path:
  pretrain_network: ~
  strict_load: true
  resume_state: ~
  train_state: ./experiments/train/EDVR
  log: ./experiments/log/EDVR
  tb_logger: ./experiments/tb_logger/EDVR

# training settings
train:
  optim:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingWarmRestarts
    T_0: 1000
    T_mult: 1
    eta_min: !!float 1e-7
    last_epoch: -1

  total_iter: 200000
  warmup_iter: -1  # no warm up
  dcn_lr_mul: 1

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: sum

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
