# general 
name: VESPCN_REDS_BDx4
model_type: VideoBaseModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: REDS4
    type: REDSDataset
    gt_dir: ../../dataset/benchmark/REDS4/GT
    lq_dir: ../../dataset/benchmark/REDS4/sharp_bicubic
    meta_info_file: ../../dataset/benchmark/REDS4/meta_info_REDS4.txt

    num_frame: 3
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true
    flip_sequence: true
    upscale: 4

    # data loader
    num_worker_per_gpu: 0
    batch_size_per_gpu: 4

  val:
    name: Vid4
    type: VideoTestDataset
    gt_dir: ../../dataset/benchmark/Vid4/GT
    lq_dir: ../../dataset/benchmark/Vid4/BDx4

    num_frame: 3  # not needed
    padding: reflection_circle

# network structures
network:
  type: VESPCN
  num_in_ch: 3
  num_out_ch: 3
  num_ch: 64
  num_feat: 24
  upscale: 4

# path
path:
  pretrain_network: ~
  strict_load: true
  resume_state: ~
  train_state: ./experiments/train/VESPCN
  log: ./expriments/log/VESPCN
  tb_logger: ./expriments/tb_logger/VESPCN  

# training settings
train:
  ema_decay: 0.999
  optim:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  total_iter: 30000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: MSELoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true