# general settings
name: BasicVSR_REDSx4
model_type: VideoRecurrentModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: REDSRecurrentDataset
    gt_dir: ./datasets/REDS/train_sharp
    lq_dir: ./datasets/REDS/train_sharp_bicubic/X4
    meta_info_file: ./data/meta_info/meta_info_REDS_GT.txt

    num_frame: 15
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 1
    batch_size_per_gpu: 4

  val:
    name: REDS4
    type: VideoRecurrentTestDataset
    gt_dir: ./datasets/REDS4/GT
    lq_dir: ./datasets/REDS4/sharp_bicubic

    num_frame: -1  # not needed

# network structures
network:
  type: BasicVSR
  num_feat: 64
  num_block: 30
  spynet_path: ./pretrained/flownet/spynet_sintel_final-3d2a1287.pth

# path
path:
  pretrain_network: ~
  strict_load: true
  resume_state: ~
  train_state: ./experiments/train/BasicVSR
  log: ./experiments/log/BasicVSR
  tb_logger: ./experiments/tb_logger/BasicVSR

# training settings
train:
  ema_decay: 0.999
  optim:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingWarmRestarts
    T_0: 500
    T_mult: 1
    eta_min: !!float 1e-7
    last_epoch: -1

  total_iter: 300000
  warmup_iter: -1  # no warm up
  fix_flow: 5000
  flow_lr_mul: 0.125

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
